apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maps-platform-staging

resources:
- ../../base/
- ../../database/
- ../../cache/
- ../../auth/
- ../../gateway/
- ../../core/
- ../../etl/
- ../../tiler/
- ../../observability/
- ../../ingress/

patches:
- path: patches/replicas.yaml

namePrefix: staging-
